export function normalizeFailureMessage(message) {
  return String(message)
    .toLowerCase()
    .replace(/[0-9a-f]{8,}/g, "<id>")
    .replace(/\b\d+\b/g, "<n>")
    .replace(/\/[^ ]+/g, "<path>")
    .replace(/\s+/g, " ")
    .trim();
}

function toFailureRecord(context, error, attempt) {
  const record = {
    asset: context.asset,
    direction: context.direction,
    attempt,
    message: error instanceof Error ? error.message : String(error),
    normalizedMessage: normalizeFailureMessage(
      error instanceof Error ? error.message : String(error),
    ),
    timestamp: new Date().toISOString(),
  };

  if (typeof context.retryable === "boolean") {
    record.retryable = context.retryable;
  }

  if (context.retryCategory) {
    record.retryCategory = context.retryCategory;
  }

  if (typeof context.retryDelayMs === "number") {
    record.retryDelayMs = context.retryDelayMs;
  }

  return record;
}

export class FailureCollector {
  constructor() {
    this.attemptFailures = [];
    this.uniqueFailures = new Map();
  }

  recordAttempt(context, error, attempt) {
    const record = toFailureRecord(context, error, attempt);
    this.attemptFailures.push(record);
    return record;
  }

  recordFinalFailure(context, error, attempt = context.retryLimit) {
    const record = toFailureRecord(context, error, attempt);
    const existing = this.uniqueFailures.get(record.normalizedMessage);

    if (existing) {
      existing.occurrences += 1;
      existing.targets.push({
        asset: context.asset,
        direction: context.direction,
        attempt,
      });
      return;
    }

    this.uniqueFailures.set(record.normalizedMessage, {
      normalizedMessage: record.normalizedMessage,
      representativeMessage: record.message,
      occurrences: 1,
      targets: [
        {
          asset: context.asset,
          direction: context.direction,
          attempt,
        },
      ],
    });
  }

  toJson() {
    return {
      attemptFailures: this.attemptFailures,
      deduplicatedFailures: Array.from(this.uniqueFailures.values()),
    };
  }
}

export function renderDeduplicatedFailuresMarkdown(uniqueFailures) {
  if (!uniqueFailures.length) {
    return "# Deduplicated Failures\n\nNo failures were recorded.\n";
  }

  const lines = ["# Deduplicated Failures", ""];

  for (const failure of uniqueFailures) {
    lines.push(`## ${failure.representativeMessage}`);
    lines.push("");
    lines.push(`- Occurrences: ${failure.occurrences}`);
    lines.push(`- Normalized key: \`${failure.normalizedMessage}\``);
    lines.push("- Affected renders:");
    for (const target of failure.targets) {
      lines.push(`  - ${target.asset} :: ${target.direction} (attempt ${target.attempt ?? "?"})`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

export function renderFailureReadme({ retryLimit, profileLabel, uniqueFailures }) {
  const lines = [
    "# Render Failure Report",
    "",
    "This file is generated by the 3D concept-art render pipeline.",
    "",
    `- Retry policy: up to ${retryLimit} attempts per asset direction`,
    "- Failure deduplication: the same normalized failure is recorded once",
    `- Active render profile: ${profileLabel}`,
    "",
  ];

  if (!uniqueFailures.length) {
    lines.push("No unique failures were recorded in the most recent run.");
    lines.push("");
    return lines.join("\n");
  }

  lines.push(`Unique failures recorded: ${uniqueFailures.length}`);
  lines.push("");

  for (const failure of uniqueFailures) {
    lines.push(`## ${failure.representativeMessage}`);
    lines.push("");
    lines.push(`- Occurrences: ${failure.occurrences}`);
    lines.push(`- Normalized key: \`${failure.normalizedMessage}\``);
    lines.push("- Affected renders:");
    for (const target of failure.targets) {
      lines.push(`  - ${target.asset} :: ${target.direction} (attempt ${target.attempt ?? "?"})`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
