export const CATEGORY_METADATA = {
  "detail-sheets": {
    label: "Detail Sheets",
    description: "Prop sheets, material studies, and building cues for the blocky splat island.",
  },
  "developed-views": {
    label: "Developed Views",
    description: "Focused zone mockups that show capture loops, traversal lanes, and study interactions.",
  },
  "gameplay-directions": {
    label: "Battlefield Studies",
    description: "Reference angles that feed the unified splat-driven island presentation.",
  },
  "main-views": {
    label: "Main Views",
    description: "High-level zone concepts for the island hub, storm lanes, and curriculum strongholds.",
  },
  references: {
    label: "References",
    description: "Player and layout anchors used to keep the island readable in motion.",
  },
  "side-games": {
    label: "Study Arenas",
    description: "Curriculum arenas for quizzes, writing, matching, and final diploma pushes.",
  },
};

export const TITLE_OVERRIDES = {
  "detail-sheets/museum-style-details.png": "Gocean Surface Details",
  "detail-sheets/review-board-development-cards.png": "Review Board Development Cards",
  "detail-sheets/roman-gallery-prop-sheet.png": "Current Archive Prop Sheet",
  "developed-views/coin-mint-demo-day2.png": "Maths Tide Lab Day 2",
  "developed-views/level-2-map-gallery-clean.png": "Sea Chart Deck",
  "gameplay-directions/direction-1-heritage-hall.png": "Kelp Bastion",
  "gameplay-directions/direction-2-marble-atrium.png": "Openwater Deck",
  "gameplay-directions/direction-3-glasshouse-museum.png": "Coral Glass Bay",
  "main-views/dusty-foyer-start.png": "Dock Zero",
  "main-views/roman-gallery-open-day1.png": "Current Archive Day 1",
  "references/curator-style-anchor.png": "Navigator Style Anchor",
  "references/foyer-layout-anchor.png": "Dock Layout Anchor",
  "side-games/curator-check-mini-game.png": "Reef Lab Mini Game",
  "side-games/estimation-mini-game.png": "Maths Tide Mini Game",
  "side-games/match-pairs-mini-game.png": "Atlas Match Mini Game",
  "side-games/mcq-mini-game.png": "Signal Deck Mini Game",
};

export const THEME_DEFINITIONS = [
  {
    id: "blockstorm-island",
    label: "Blockstorm Island",
    asset: "main-views/dusty-foyer-start.png",
    starterRoomId: "foyer",
    description:
      "One large blocky island with landing pads, buildable ridges, splat landmarks, and curriculum strongholds.",
    palette: {
      accent: "#f59b42",
      deep: "#173235",
      highlight: "#f4edd6",
      shadow: "#0a1d22",
    },
  },
];

export const ROOM_BLUEPRINTS = [
  {
    id: "foyer",
    label: "Drop Harbor",
    artAsset: "main-views/dusty-foyer-start.png",
    previewAsset: "references/foyer-layout-anchor.png",
    blurb: "The central landing harbor where each run starts, early pickups spawn, and the whole island opens out around the player.",
    cost: 0,
    diplomaRequirement: 0,
    startUnlocked: true,
    requiredRoomIds: [],
    immersiveNeighbors: ["hotline-desk", "heritage-hall", "marble-atrium", "glasshouse-rotunda"],
    position: { x: 54, y: 278, width: 178, height: 138 },
    rewardRate: 1,
  },
  {
    id: "heritage-hall",
    label: "Brick Bastion",
    artAsset: "gameplay-directions/direction-1-heritage-hall.png",
    previewAsset: "main-views/roman-gallery-open-day1.png",
    blurb: "A chunky red-stone stronghold with early loot lines, short build cover, and English-heavy opening missions.",
    cost: 34,
    diplomaRequirement: 1,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer", "roman-gallery"],
    position: { x: 258, y: 226, width: 214, height: 146 },
    rewardRate: 2,
  },
  {
    id: "marble-atrium",
    label: "Skyforge Plaza",
    artAsset: "gameplay-directions/direction-2-marble-atrium.png",
    previewAsset: "developed-views/level-2-map-gallery-clean.png",
    blurb: "A bright block-built plaza with long sightlines, fast rotation routes, and maths-focused objective lanes.",
    cost: 38,
    diplomaRequirement: 2,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer", "coin-mint-lab"],
    position: { x: 258, y: 392, width: 214, height: 146 },
    rewardRate: 2,
  },
  {
    id: "glasshouse-rotunda",
    label: "Canopy Commons",
    artAsset: "gameplay-directions/direction-3-glasshouse-museum.png",
    previewAsset: "references/curator-style-anchor.png",
    blurb: "A tropical commons with stacked glass cover, bounce routes, splat landmarks, and flexible study detours.",
    cost: 42,
    diplomaRequirement: 2,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer", "curiosity-arcade"],
    position: { x: 486, y: 308, width: 220, height: 160 },
    rewardRate: 2,
  },
  {
    id: "roman-gallery",
    label: "Diploma Citadel",
    artAsset: "main-views/roman-gallery-open-day1.png",
    previewAsset: "detail-sheets/roman-gallery-prop-sheet.png",
    blurb: "A high-tier capture citadel with denser cover, larger splat landmarks, and stronger diploma-route rewards.",
    cost: 58,
    diplomaRequirement: 3,
    startUnlocked: false,
    requiredRoomIds: ["heritage-hall"],
    immersiveNeighbors: ["heritage-hall", "review-studio"],
    position: { x: 722, y: 204, width: 212, height: 146 },
    rewardRate: 3,
  },
  {
    id: "coin-mint-lab",
    label: "Craft Quarry",
    artAsset: "developed-views/coin-mint-demo-day2.png",
    previewAsset: "side-games/estimation-mini-game.png",
    blurb: "A quarry arena for hard Year 6 maths, fast resource farming, and build-up toward diploma finals.",
    cost: 46,
    diplomaRequirement: 3,
    startUnlocked: false,
    requiredRoomIds: ["marble-atrium"],
    immersiveNeighbors: ["marble-atrium"],
    position: { x: 720, y: 384, width: 214, height: 146 },
    rewardRate: 3,
    miniGameId: "estimation",
  },
  {
    id: "hotline-desk",
    label: "Signal Forge",
    artAsset: "references/curator-style-anchor.png",
    previewAsset: "side-games/mcq-mini-game.png",
    blurb: "A close-range forge for reading, writing, model answers, and rewrite quests across tougher English prompts.",
    cost: 28,
    diplomaRequirement: 1,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer"],
    position: { x: 54, y: 92, width: 178, height: 136 },
    rewardRate: 2,
    miniGameId: "study-quiz",
  },
  {
    id: "review-studio",
    label: "Storm Lab",
    artAsset: "detail-sheets/review-board-development-cards.png",
    previewAsset: "side-games/curator-check-mini-game.png",
    blurb: "A storm-charged science arena for sharper reasoning rounds, follow-up quests, and final diploma checks.",
    cost: 52,
    diplomaRequirement: 4,
    startUnlocked: false,
    requiredRoomIds: ["roman-gallery"],
    immersiveNeighbors: ["roman-gallery"],
    position: { x: 952, y: 108, width: 140, height: 148 },
    rewardRate: 4,
    miniGameId: "curator-check",
  },
  {
    id: "curiosity-arcade",
    label: "Atlas Arena",
    artAsset: "detail-sheets/museum-style-details.png",
    previewAsset: "side-games/match-pairs-mini-game.png",
    blurb: "A humanities arena that mixes history, geography, and vocabulary drills into faster match-heavy skirmishes.",
    cost: 54,
    diplomaRequirement: 4,
    startUnlocked: false,
    requiredRoomIds: ["glasshouse-rotunda"],
    immersiveNeighbors: ["glasshouse-rotunda"],
    position: { x: 952, y: 432, width: 140, height: 148 },
    rewardRate: 4,
    miniGameId: "match-pairs",
  },
];
