export const CATEGORY_METADATA = {
  "detail-sheets": {
    label: "Detail Sheets",
    description: "Navigation props, route boards, and art-language sheets that define the Gocean splat world.",
  },
  "developed-views": {
    label: "Developed Views",
    description: "Focused zone mockups that show specific loops, splat travel, and study interactions.",
  },
  "gameplay-directions": {
    label: "Gameplay Directions",
    description: "The three major visual directions for the playable Gocean splat map.",
  },
  "main-views": {
    label: "Main Views",
    description: "High-level zone concepts for the dock and archive routes.",
  },
  references: {
    label: "References",
    description: "Navigator and layout anchors used to keep the route readable.",
  },
  "side-games": {
    label: "Side Games",
    description: "Lightweight Gocean study-hub concepts for quizzes, writing, and reef-lab checks.",
  },
};

export const TITLE_OVERRIDES = {
  "detail-sheets/museum-style-details.png": "Gocean Surface Details",
  "detail-sheets/review-board-development-cards.png": "Review Board Development Cards",
  "detail-sheets/roman-gallery-prop-sheet.png": "Current Archive Prop Sheet",
  "developed-views/coin-mint-demo-day2.png": "Maths Tide Lab Day 2",
  "developed-views/level-2-map-gallery-clean.png": "Sea Chart Deck",
  "gameplay-directions/direction-1-heritage-hall.png": "Kelp Bastion",
  "gameplay-directions/direction-2-marble-atrium.png": "Openwater Deck",
  "gameplay-directions/direction-3-glasshouse-museum.png": "Coral Glass Bay",
  "main-views/dusty-foyer-start.png": "Dock Zero",
  "main-views/roman-gallery-open-day1.png": "Current Archive Day 1",
  "references/curator-style-anchor.png": "Navigator Style Anchor",
  "references/foyer-layout-anchor.png": "Dock Layout Anchor",
  "side-games/curator-check-mini-game.png": "Reef Lab Mini Game",
  "side-games/estimation-mini-game.png": "Maths Tide Mini Game",
  "side-games/match-pairs-mini-game.png": "Atlas Match Mini Game",
  "side-games/mcq-mini-game.png": "Signal Deck Mini Game",
};

export const THEME_DEFINITIONS = [
  {
    id: "heritage-hall",
    label: "Kelp Bastion",
    asset: "gameplay-directions/direction-1-heritage-hall.png",
    starterRoomId: "heritage-hall",
    description:
      "Deep green lanes, brass trim, and shadowed currents for a sturdy harbor-route mood.",
    palette: {
      accent: "#c79f58",
      deep: "#17352f",
      highlight: "#f4ead9",
      shadow: "#092017",
    },
  },
  {
    id: "marble-atrium",
    label: "Openwater Deck",
    asset: "gameplay-directions/direction-2-marble-atrium.png",
    starterRoomId: "marble-atrium",
    description:
      "Bright stone surfaces, skylit water glare, and teal lanes for a clean ocean-campus route.",
    palette: {
      accent: "#4aa8a7",
      deep: "#194250",
      highlight: "#eef4f5",
      shadow: "#0d2630",
    },
  },
  {
    id: "glasshouse-museum",
    label: "Coral Glass Bay",
    asset: "gameplay-directions/direction-3-glasshouse-museum.png",
    starterRoomId: "glasshouse-rotunda",
    description:
      "Glass partitions, reef tones, and terracotta decks for a softer tropical splat atmosphere.",
    palette: {
      accent: "#d17d43",
      deep: "#21433f",
      highlight: "#fbf1dd",
      shadow: "#122725",
    },
  },
];

export const ROOM_BLUEPRINTS = [
  {
    id: "foyer",
    label: "Dock Zero",
    artAsset: "main-views/dusty-foyer-start.png",
    previewAsset: "references/foyer-layout-anchor.png",
    blurb: "The starting dock where the navigator launches a run, gathers early drift coins, and chooses the day's route.",
    cost: 0,
    diplomaRequirement: 0,
    startUnlocked: true,
    requiredRoomIds: [],
    immersiveNeighbors: ["hotline-desk", "heritage-hall", "marble-atrium", "glasshouse-rotunda"],
    position: { x: 54, y: 278, width: 178, height: 138 },
    rewardRate: 1,
  },
  {
    id: "heritage-hall",
    label: "Kelp Bastion Route",
    artAsset: "gameplay-directions/direction-1-heritage-hall.png",
    previewAsset: "main-views/roman-gallery-open-day1.png",
    blurb: "A dense kelp-lined route with early coin drift, locked future passages, and steady traffic.",
    cost: 34,
    diplomaRequirement: 1,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer", "roman-gallery"],
    position: { x: 258, y: 226, width: 214, height: 146 },
    rewardRate: 2,
  },
  {
    id: "marble-atrium",
    label: "Openwater Transit",
    artAsset: "gameplay-directions/direction-2-marble-atrium.png",
    previewAsset: "developed-views/level-2-map-gallery-clean.png",
    blurb: "A bright openwater lane with long sightlines and clear links into later study zones.",
    cost: 38,
    diplomaRequirement: 2,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer", "coin-mint-lab"],
    position: { x: 258, y: 392, width: 214, height: 146 },
    rewardRate: 2,
  },
  {
    id: "glasshouse-rotunda",
    label: "Coral Glass Bay",
    artAsset: "gameplay-directions/direction-3-glasshouse-museum.png",
    previewAsset: "references/curator-style-anchor.png",
    blurb: "A reef-lit hub that branches into side activities, splat scenes, and softer tropical study routes.",
    cost: 42,
    diplomaRequirement: 2,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer", "curiosity-arcade"],
    position: { x: 486, y: 308, width: 220, height: 160 },
    rewardRate: 2,
  },
  {
    id: "roman-gallery",
    label: "Current Archive",
    artAsset: "main-views/roman-gallery-open-day1.png",
    previewAsset: "detail-sheets/roman-gallery-prop-sheet.png",
    blurb: "A higher-value archive current with denser prop language, stronger splat travel, and richer guided-route rewards.",
    cost: 58,
    diplomaRequirement: 3,
    startUnlocked: false,
    requiredRoomIds: ["heritage-hall"],
    immersiveNeighbors: ["heritage-hall", "review-studio"],
    position: { x: 722, y: 204, width: 212, height: 146 },
    rewardRate: 3,
  },
  {
    id: "coin-mint-lab",
    label: "Maths Tide Lab",
    artAsset: "developed-views/coin-mint-demo-day2.png",
    previewAsset: "side-games/estimation-mini-game.png",
    blurb: "A Year 6 maths zone for hard reasoning prompts, quick working, and diploma-building practice.",
    cost: 46,
    diplomaRequirement: 3,
    startUnlocked: false,
    requiredRoomIds: ["marble-atrium"],
    immersiveNeighbors: ["marble-atrium"],
    position: { x: 720, y: 384, width: 214, height: 146 },
    rewardRate: 3,
    miniGameId: "estimation",
  },
  {
    id: "hotline-desk",
    label: "Signal Deck English",
    artAsset: "references/curator-style-anchor.png",
    previewAsset: "side-games/mcq-mini-game.png",
    blurb: "A signal deck for reading, writing, model answers, and rewrite tasks across the hardest Year 6 prompts.",
    cost: 28,
    diplomaRequirement: 1,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer"],
    position: { x: 54, y: 92, width: 178, height: 136 },
    rewardRate: 2,
    miniGameId: "study-quiz",
  },
  {
    id: "review-studio",
    label: "Reef Lab Science",
    artAsset: "detail-sheets/review-board-development-cards.png",
    previewAsset: "side-games/curator-check-mini-game.png",
    blurb: "A reef lab for challenging science and reasoning rounds that feed quests and final diploma checks.",
    cost: 52,
    diplomaRequirement: 4,
    startUnlocked: false,
    requiredRoomIds: ["roman-gallery"],
    immersiveNeighbors: ["roman-gallery"],
    position: { x: 952, y: 108, width: 140, height: 148 },
    rewardRate: 4,
    miniGameId: "curator-check",
  },
  {
    id: "curiosity-arcade",
    label: "Atlas Reef Match Deck",
    artAsset: "detail-sheets/museum-style-details.png",
    previewAsset: "side-games/match-pairs-mini-game.png",
    blurb: "A Year 6 history and geography deck that mixes matching practice with tougher quiz rounds.",
    cost: 54,
    diplomaRequirement: 4,
    startUnlocked: false,
    requiredRoomIds: ["glasshouse-rotunda"],
    immersiveNeighbors: ["glasshouse-rotunda"],
    position: { x: 952, y: 432, width: 140, height: 148 },
    rewardRate: 4,
    miniGameId: "match-pairs",
  },
];
