export const CATEGORY_METADATA = {
  "detail-sheets": {
    label: "Detail Sheets",
    description: "Props, review boards, and art-language sheets that define museum surfaces and objects.",
  },
  "developed-views": {
    label: "Developed Views",
    description: "Focused environment mockups that show specific loops and room interactions.",
  },
  "gameplay-directions": {
    label: "Gameplay Directions",
    description: "The three major visual directions for the playable museum floor.",
  },
  "main-views": {
    label: "Main Views",
    description: "High-level room concepts for the foyer and the Roman gallery.",
  },
  references: {
    label: "References",
    description: "Character and layout anchors used to keep the curator and flow readable.",
  },
  "side-games": {
    label: "Side Games",
    description: "Lightweight museum mini-game concepts for trivia, estimation, and curator checks.",
  },
};

export const TITLE_OVERRIDES = {
  "detail-sheets/museum-style-details.png": "Museum Style Details",
  "detail-sheets/review-board-development-cards.png": "Review Board Development Cards",
  "detail-sheets/roman-gallery-prop-sheet.png": "Roman Gallery Prop Sheet",
  "developed-views/coin-mint-demo-day2.png": "Coin Mint Demo Day 2",
  "developed-views/level-2-map-gallery-clean.png": "Level 2 Map Gallery",
  "gameplay-directions/direction-1-heritage-hall.png": "Heritage Hall",
  "gameplay-directions/direction-2-marble-atrium.png": "Marble Atrium",
  "gameplay-directions/direction-3-glasshouse-museum.png": "Glasshouse Museum",
  "main-views/dusty-foyer-start.png": "Dusty Foyer Start",
  "main-views/roman-gallery-open-day1.png": "Roman Gallery Open Day 1",
  "references/curator-style-anchor.png": "Curator Style Anchor",
  "references/foyer-layout-anchor.png": "Foyer Layout Anchor",
  "side-games/curator-check-mini-game.png": "Curator Check Mini Game",
  "side-games/estimation-mini-game.png": "Estimation Mini Game",
  "side-games/match-pairs-mini-game.png": "Match Pairs Mini Game",
  "side-games/mcq-mini-game.png": "MCQ Mini Game",
};

export const THEME_DEFINITIONS = [
  {
    id: "heritage-hall",
    label: "Heritage Hall",
    asset: "gameplay-directions/direction-1-heritage-hall.png",
    starterRoomId: "heritage-hall",
    description:
      "Dark green stripes, parquet flooring, and brass warmth for a classic heritage-museum mood.",
    palette: {
      accent: "#c79f58",
      deep: "#17352f",
      highlight: "#f4ead9",
      shadow: "#092017",
    },
  },
  {
    id: "marble-atrium",
    label: "Marble Atrium",
    asset: "gameplay-directions/direction-2-marble-atrium.png",
    starterRoomId: "marble-atrium",
    description:
      "Bright stone surfaces, skylit space, and teal accents for a formal institutional wing.",
    palette: {
      accent: "#4aa8a7",
      deep: "#194250",
      highlight: "#eef4f5",
      shadow: "#0d2630",
    },
  },
  {
    id: "glasshouse-museum",
    label: "Glasshouse Museum",
    asset: "gameplay-directions/direction-3-glasshouse-museum.png",
    starterRoomId: "glasshouse-rotunda",
    description:
      "Glass partitions, plants, terracotta surfaces, and a softer modern museum atmosphere.",
    palette: {
      accent: "#d17d43",
      deep: "#21433f",
      highlight: "#fbf1dd",
      shadow: "#122725",
    },
  },
];

export const ROOM_BLUEPRINTS = [
  {
    id: "foyer",
    label: "Dusty Foyer",
    artAsset: "main-views/dusty-foyer-start.png",
    previewAsset: "references/foyer-layout-anchor.png",
    blurb: "The opening lobby where the curator grabs early ticket income and sets the day's route.",
    cost: 0,
    startUnlocked: true,
    requiredRoomIds: [],
    immersiveNeighbors: ["hotline-desk", "heritage-hall", "marble-atrium", "glasshouse-rotunda"],
    position: { x: 54, y: 278, width: 178, height: 138 },
    rewardRate: 1,
  },
  {
    id: "heritage-hall",
    label: "Heritage Hall Wing",
    artAsset: "gameplay-directions/direction-1-heritage-hall.png",
    previewAsset: "main-views/roman-gallery-open-day1.png",
    blurb: "A warm heritage corridor with coins, locked future space, and dense visitor circulation.",
    cost: 34,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer", "roman-gallery"],
    position: { x: 258, y: 226, width: 214, height: 146 },
    rewardRate: 2,
  },
  {
    id: "marble-atrium",
    label: "Marble Atrium",
    artAsset: "gameplay-directions/direction-2-marble-atrium.png",
    previewAsset: "developed-views/level-2-map-gallery-clean.png",
    blurb: "A brighter, more formal route with skylight volume and clear long-range sightlines.",
    cost: 38,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer", "coin-mint-lab"],
    position: { x: 258, y: 392, width: 214, height: 146 },
    rewardRate: 2,
  },
  {
    id: "glasshouse-rotunda",
    label: "Glasshouse Rotunda",
    artAsset: "gameplay-directions/direction-3-glasshouse-museum.png",
    previewAsset: "references/curator-style-anchor.png",
    blurb: "A softer glass-and-plant hub that branches into modern exhibits and side activities.",
    cost: 42,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer", "curiosity-arcade"],
    position: { x: 486, y: 308, width: 220, height: 160 },
    rewardRate: 2,
  },
  {
    id: "roman-gallery",
    label: "Roman Gallery",
    artAsset: "main-views/roman-gallery-open-day1.png",
    previewAsset: "detail-sheets/roman-gallery-prop-sheet.png",
    blurb: "A higher-value exhibit hall with stronger prop language and richer guided-tour rewards.",
    cost: 58,
    startUnlocked: false,
    requiredRoomIds: ["heritage-hall"],
    immersiveNeighbors: ["heritage-hall", "review-studio"],
    position: { x: 722, y: 204, width: 212, height: 146 },
    rewardRate: 3,
  },
  {
    id: "coin-mint-lab",
    label: "Coin Mint Lab",
    artAsset: "developed-views/coin-mint-demo-day2.png",
    previewAsset: "side-games/estimation-mini-game.png",
    blurb: "A hands-on room where estimation rounds turn curiosity into money and reputation.",
    cost: 46,
    startUnlocked: false,
    requiredRoomIds: ["marble-atrium"],
    immersiveNeighbors: ["marble-atrium"],
    position: { x: 720, y: 384, width: 214, height: 146 },
    rewardRate: 3,
    miniGameId: "estimation",
  },
  {
    id: "hotline-desk",
    label: "Call The Curator Desk",
    artAsset: "references/curator-style-anchor.png",
    previewAsset: "side-games/mcq-mini-game.png",
    blurb: "A public hotline station for answering museum questions without dropping the floor loop.",
    cost: 28,
    startUnlocked: false,
    requiredRoomIds: ["foyer"],
    immersiveNeighbors: ["foyer"],
    position: { x: 54, y: 92, width: 178, height: 136 },
    rewardRate: 2,
    miniGameId: "study-quiz",
  },
  {
    id: "review-studio",
    label: "Review Studio",
    artAsset: "detail-sheets/review-board-development-cards.png",
    previewAsset: "side-games/curator-check-mini-game.png",
    blurb: "A design review room for curator checks and visitor-response triage.",
    cost: 52,
    startUnlocked: false,
    requiredRoomIds: ["roman-gallery"],
    immersiveNeighbors: ["roman-gallery"],
    position: { x: 952, y: 108, width: 140, height: 148 },
    rewardRate: 4,
    miniGameId: "curator-check",
  },
  {
    id: "curiosity-arcade",
    label: "Curiosity Arcade",
    artAsset: "detail-sheets/museum-style-details.png",
    previewAsset: "side-games/match-pairs-mini-game.png",
    blurb: "A family-friendly memory space that converts playful side-games into museum buzz.",
    cost: 54,
    startUnlocked: false,
    requiredRoomIds: ["glasshouse-rotunda"],
    immersiveNeighbors: ["glasshouse-rotunda"],
    position: { x: 952, y: 432, width: 140, height: 148 },
    rewardRate: 4,
    miniGameId: "match-pairs",
  },
];
